/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yo */
        get: operations["yo_api_auth_yo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dia/actual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dia Actual */
        get: operations["dia_actual_api_dia_actual_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dia/abrir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dia Abrir */
        post: operations["dia_abrir_api_dia_abrir_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dia/{dia_id}/cerrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dia Cerrar */
        post: operations["dia_cerrar_api_dia__dia_id__cerrar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turno/{turno_id}/ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turno Ticket */
        post: operations["turno_ticket_api_turno__turno_id__ticket_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movimientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Movimientos */
        get: operations["listar_movimientos_api_movimientos_get"];
        put?: never;
        /** Crear Movimiento */
        post: operations["crear_movimiento_api_movimientos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movimientos/{movimiento_id}/anular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anular Movimiento */
        post: operations["anular_movimiento_api_movimientos__movimiento_id__anular_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traspaso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Traspaso */
        post: operations["traspaso_api_traspaso_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arqueo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arqueo */
        post: operations["arqueo_api_arqueo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rendicion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rendicion */
        post: operations["rendicion_api_rendicion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cajas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Cajas */
        get: operations["listar_cajas_api_cajas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/juegos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Juegos */
        get: operations["listar_juegos_api_juegos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clientes/deudores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clientes Deudores */
        get: operations["clientes_deudores_api_clientes_deudores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar Clientes */
        get: operations["buscar_clientes_api_clientes_get"];
        put?: never;
        /** Crear Cliente */
        post: operations["crear_cliente_api_clientes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clientes/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle Cliente */
        get: operations["detalle_cliente_api_clientes__cliente_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reportes/dia/{fecha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reporte Dia */
        get: operations["reporte_dia_api_reportes_dia__fecha__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reportes/diferencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reporte Diferencias */
        get: operations["reporte_diferencias_api_reportes_diferencias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reportes/mercado-pago": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reporte Mercado Pago */
        get: operations["reporte_mercado_pago_api_reportes_mercado_pago_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reportes/ventas-por-juego": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reporte Ventas Por Juego */
        get: operations["reporte_ventas_por_juego_api_reportes_ventas_por_juego_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reportes/rendiciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reporte Rendiciones */
        get: operations["reporte_rendiciones_api_reportes_rendiciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reportes/mes/{mes}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reporte Mes */
        get: operations["reporte_mes_api_reportes_mes__mes__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asistente": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preguntar
         * @description §11.3: fuera del camino crítico. Sin clave (o vacía, como la pasa compose) o con la API caída, 503 y el resto
         *     del sistema sigue igual. No se loguean preguntas ni respuestas: traen datos de clientes.
         */
        post: operations["preguntar_api_asistente_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Salud */
        get: operations["salud_api_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnularRequest */
        AnularRequest: {
            /** Motivo */
            motivo: string;
        };
        /** ArqueoOut */
        ArqueoOut: {
            /** Id */
            id: number;
            /** Efectivo Esperado */
            efectivo_esperado: number;
            /** Boletas Esperadas */
            boletas_esperadas: number;
            /** Diferencia Efectivo */
            diferencia_efectivo: number;
            /** Diferencia Boletas */
            diferencia_boletas: number;
            /**
             * Estado
             * @enum {string}
             */
            estado: "cuadra" | "con_diferencia" | "explicada";
        };
        /** ArqueoRequest */
        ArqueoRequest: {
            /** Caja Id */
            caja_id: number;
            /** Turno Id */
            turno_id: number;
            /** Efectivo Contado */
            efectivo_contado: number;
            /** Boletas Contadas */
            boletas_contadas: number;
            /** Nota */
            nota?: string | null;
        };
        /** AsistenteOut */
        AsistenteOut: {
            /** Respuesta */
            respuesta: string;
            /** Tools Usadas */
            tools_usadas: string[];
        };
        /** AsistenteRequest */
        AsistenteRequest: {
            /** Pregunta */
            pregunta: string;
            /** Arqueo Id */
            arqueo_id?: number | null;
        };
        /** CajaEstado */
        CajaEstado: {
            /** Efectivo */
            efectivo: number;
            /** Boletas */
            boletas: number;
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "operativa" | "central";
            esperado?: components["schemas"]["Saldo"] | null;
        };
        /** ClienteBusqueda */
        ClienteBusqueda: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Saldo */
            saldo: number;
        };
        /** ClienteCrear */
        ClienteCrear: {
            /** Nombre */
            nombre: string;
            /** Alias */
            alias?: string | null;
            /** Telefono */
            telefono?: string | null;
        };
        /** ClienteDetalle */
        ClienteDetalle: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Saldo */
            saldo: number;
            /** Movimientos */
            movimientos: components["schemas"]["MovimientoOut"][];
        };
        /** Desglose */
        Desglose: {
            /** Quiniela */
            quiniela: number;
            /** Otros Juegos */
            otros_juegos: number;
            /** Cobros */
            cobros: number;
            /** Fiados */
            fiados: number;
            /** Mercado Pago */
            mercado_pago: number;
            /** Premios */
            premios: number;
            /** Otros Pagos */
            otros_pagos: number;
        };
        /** DeudorOut */
        DeudorOut: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Saldo */
            saldo: number;
            /** Dias Deuda Mas Vieja */
            dias_deuda_mas_vieja: number;
        };
        /** DiaActualOut */
        DiaActualOut: {
            dia: components["schemas"]["DiaOut"];
            /** Rendicion Pendiente */
            rendicion_pendiente: boolean;
            /** Turnos */
            turnos: components["schemas"]["TurnoOut"][];
            /** Cajas */
            cajas: components["schemas"]["CajaEstado"][];
            /** Arqueos Pendientes */
            arqueos_pendientes: string[];
        };
        /** DiaConTurnos */
        DiaConTurnos: {
            dia: components["schemas"]["DiaOut"];
            /** Turnos */
            turnos: components["schemas"]["TurnoOut"][];
        };
        /** DiaOut */
        DiaOut: {
            /** Id */
            id: number;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /**
             * Estado
             * @enum {string}
             */
            estado: "abierto" | "cerrado";
        };
        /** DiferenciaItem */
        DiferenciaItem: {
            /** Id */
            id: number;
            /** Caja Id */
            caja_id: number;
            /** Turno Id */
            turno_id: number;
            /**
             * Momento
             * Format: date-time
             */
            momento: string;
            /** Diferencia Efectivo */
            diferencia_efectivo: number;
            /** Diferencia Boletas */
            diferencia_boletas: number;
            /**
             * Estado
             * @enum {string}
             */
            estado: "cuadra" | "con_diferencia" | "explicada";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JuegoMonto */
        JuegoMonto: {
            /** Juego Id */
            juego_id: number;
            /** Monto */
            monto: number;
        };
        /** JuegoOut */
        JuegoOut: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Usuario */
            usuario: string;
            /** Password */
            password: string;
        };
        /** MovimientoCrear */
        MovimientoCrear: {
            /**
             * Ref Cliente
             * Format: uuid
             */
            ref_cliente: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "fiado" | "cobro_fiado" | "cobro_subagente" | "ingreso_del_dueno" | "cobro_mercado_pago" | "pago_premio" | "pago_banco" | "sueldo" | "gasto" | "retiro_dueno";
            /** Monto */
            monto: number;
            /** Caja Id */
            caja_id: number;
            /** Cliente Id */
            cliente_id?: number | null;
            /** Contraparte */
            contraparte?: string | null;
            /** Nota */
            nota?: string | null;
            /** Corresponde A Fecha */
            corresponde_a_fecha?: string | null;
            /** Explica Arqueo Id */
            explica_arqueo_id?: number | null;
        };
        /** MovimientoOut */
        MovimientoOut: {
            /** Id */
            id: number;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "apuesta_quiniela" | "venta_otro_juego" | "fiado" | "cobro_fiado" | "cobro_subagente" | "ingreso_del_dueno" | "cobro_mercado_pago" | "pago_premio" | "pago_banco" | "sueldo" | "gasto" | "retiro_dueno" | "traspaso" | "traspaso_boletas" | "rendicion_boletas";
            /** Monto */
            monto: number;
            /** Caja Id */
            caja_id: number;
            /** Turno Id */
            turno_id: number;
            /** Cliente Id */
            cliente_id: number | null;
            /** Cliente Nombre */
            cliente_nombre?: string | null;
            /** Juego Id */
            juego_id: number | null;
            /** Contraparte */
            contraparte: string | null;
            /** Nota */
            nota: string | null;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Corresponde A Fecha
             * Format: date
             */
            corresponde_a_fecha: string;
            /** Es Ajuste */
            es_ajuste: boolean;
            /** Anula Id */
            anula_id: number | null;
            /** Motivo Anulacion */
            motivo_anulacion: string | null;
            /** Explica Arqueo Id */
            explica_arqueo_id: number | null;
        };
        /** MovimientosPagina */
        MovimientosPagina: {
            /** Items */
            items: components["schemas"]["MovimientoOut"][];
            /** Total */
            total: number;
            /** Pagina */
            pagina: number;
        };
        /** NegocioOut */
        NegocioOut: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
        };
        /** RendicionItem */
        RendicionItem: {
            /** Id */
            id: number;
            /** Total Esperado */
            total_esperado: number;
            /** Total Contado */
            total_contado: number;
            /** Diferencia */
            diferencia: number;
            /** Cantidad Boletas */
            cantidad_boletas: number;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
        };
        /** RendicionOut */
        RendicionOut: {
            /** Id */
            id: number;
            /** Total Esperado */
            total_esperado: number;
            /** Total Contado */
            total_contado: number;
            /** Diferencia */
            diferencia: number;
            /** Cantidad Boletas */
            cantidad_boletas: number;
        };
        /** RendicionRequest */
        RendicionRequest: {
            /** Boletas Contadas */
            boletas_contadas: number;
        };
        /** ReporteDia */
        ReporteDia: {
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Totales Por Tipo */
            totales_por_tipo: {
                [key: string]: number;
            };
            /** Apuestas */
            apuestas: number;
            /** Boletas */
            boletas: number;
            /** Arqueos */
            arqueos: components["schemas"]["ArqueoOut"][];
        };
        /** ReporteMercadoPago */
        ReporteMercadoPago: {
            /** Acumulado */
            acumulado: number;
            /** Desde */
            desde: string | null;
        };
        /** ReporteMes */
        ReporteMes: {
            /** Mes */
            mes: string;
            actual: components["schemas"]["ResumenMes"];
            anterior: components["schemas"]["ResumenMes"];
            /** Deuda Total Hoy */
            deuda_total_hoy: number;
            /** Ventas Por Dia */
            ventas_por_dia: components["schemas"]["VentaDia"][];
        };
        /** ResumenMes */
        ResumenMes: {
            /** Ventas Por Juego */
            ventas_por_juego: components["schemas"]["VentaJuegoMes"][];
            /** Total Vendido */
            total_vendido: number;
            /** Cobros Fiado */
            cobros_fiado: number;
            /** Cobros Subagente */
            cobros_subagente: number;
            /** Ingresos Del Dueno */
            ingresos_del_dueno: number;
            /** Premios Pagados */
            premios_pagados: number;
            /** Cobros Mercado Pago */
            cobros_mercado_pago: number;
            /** Pagos Banco */
            pagos_banco: number;
            /** Sueldos */
            sueldos: number;
            /** Gastos */
            gastos: number;
            /** Retiros Dueno */
            retiros_dueno: number;
            /** Fiado */
            fiado: number;
            /** Arqueos Hechos */
            arqueos_hechos: number;
            /** Arqueos Cuadran */
            arqueos_cuadran: number;
            /** Arqueos Con Diferencia */
            arqueos_con_diferencia: number;
            /** Arqueos Explicados */
            arqueos_explicados: number;
            /** Diferencia Efectivo */
            diferencia_efectivo: number;
            /** Diferencia Boletas */
            diferencia_boletas: number;
            /** Diferencia Total */
            diferencia_total: number;
        };
        /** Saldo */
        Saldo: {
            /** Efectivo */
            efectivo: number;
            /** Boletas */
            boletas: number;
        };
        /** TicketOut */
        TicketOut: {
            esperado: components["schemas"]["Saldo"];
            desglose: components["schemas"]["Desglose"];
        };
        /** TicketRequest */
        TicketRequest: {
            /** Quiniela */
            quiniela: number;
            /** Juegos */
            juegos: components["schemas"]["JuegoMonto"][];
        };
        /** TraspasoRequest */
        TraspasoRequest: {
            /** Caja Origen Id */
            caja_origen_id: number;
        };
        /** TurnoOut */
        TurnoOut: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /**
             * Estado
             * @enum {string}
             */
            estado: "abierto" | "cerrado";
            /** Tiene Ticket */
            tiene_ticket: boolean;
        };
        /** UsuarioOut */
        UsuarioOut: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            negocio: components["schemas"]["NegocioOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VentaDia */
        VentaDia: {
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Total */
            total: number;
        };
        /** VentaJuegoItem */
        VentaJuegoItem: {
            /** Periodo */
            periodo: string;
            /** Juego Id */
            juego_id: number;
            /** Total */
            total: number;
        };
        /** VentaJuegoMes */
        VentaJuegoMes: {
            /** Juego Id */
            juego_id: number;
            /** Nombre */
            nombre: string;
            /** Total */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yo_api_auth_yo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dia_actual_api_dia_actual_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaActualOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dia_abrir_api_dia_abrir_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaConTurnos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dia_cerrar_api_dia__dia_id__cerrar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dia_id: number;
            };
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turno_ticket_api_turno__turno_id__ticket_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turno_id: number;
            };
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_movimientos_api_movimientos_get: {
        parameters: {
            query?: {
                turno_id?: number | null;
                caja_id?: number | null;
                tipo?: ("apuesta_quiniela" | "venta_otro_juego" | "fiado" | "cobro_fiado" | "cobro_subagente" | "ingreso_del_dueno" | "cobro_mercado_pago" | "pago_premio" | "pago_banco" | "sueldo" | "gasto" | "retiro_dueno" | "traspaso" | "traspaso_boletas" | "rendicion_boletas") | null;
                cliente_id?: number | null;
                desde?: string | null;
                hasta?: string | null;
                pagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovimientosPagina"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_movimiento_api_movimientos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovimientoCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovimientoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anular_movimiento_api_movimientos__movimiento_id__anular_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movimiento_id: number;
            };
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnularRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovimientoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    traspaso_api_traspaso_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TraspasoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saldo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arqueo_api_arqueo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArqueoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArqueoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rendicion_api_rendicion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RendicionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RendicionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_cajas_api_cajas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CajaEstado"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_juegos_api_juegos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JuegoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clientes_deudores_api_clientes_deudores_get: {
        parameters: {
            query?: {
                orden?: "monto" | "antiguedad";
            };
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeudorOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_clientes_api_clientes_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteBusqueda"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_cliente_api_clientes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteBusqueda"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detalle_cliente_api_clientes__cliente_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: number;
            };
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteDetalle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reporte_dia_api_reportes_dia__fecha__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fecha: string;
            };
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReporteDia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reporte_diferencias_api_reportes_diferencias_get: {
        parameters: {
            query?: {
                desde?: string | null;
                hasta?: string | null;
                caja_id?: number | null;
                turno?: ("mañana" | "noche") | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiferenciaItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reporte_mercado_pago_api_reportes_mercado_pago_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReporteMercadoPago"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reporte_ventas_por_juego_api_reportes_ventas_por_juego_get: {
        parameters: {
            query?: {
                desde?: string | null;
                hasta?: string | null;
                agrupar?: "dia" | "semana" | "mes";
            };
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VentaJuegoItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reporte_rendiciones_api_reportes_rendiciones_get: {
        parameters: {
            query?: {
                desde?: string | null;
                hasta?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RendicionItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reporte_mes_api_reportes_mes__mes__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mes: string;
            };
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReporteMes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preguntar_api_asistente_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sesion?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AsistenteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsistenteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    salud_api_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
